<?php
# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.5 on 17/01/2015 at 09:35:21
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------


// Receiving variables
@$pfw_ip= $_SERVER['REMOTE_ADDR'];
@$username = addslashes($_GET['username']);
@$email = addslashes($_GET['email']);

// Validation
if (strlen($username) == 0 )
{
header("Location: error.html");
exit;
}

if (! ereg('[A-Za-z0-9_-]+\@[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+', $email))
{
header("Location: error.html");
exit;
}

if (strlen($email) == 0 )
{
header("Location: error.html");
exit;
}

//Sending Email to form owner
$pfw_header = "From: $email\n"
  . "Reply-To: $email\n";
$pfw_subject = "Testing Email with php form wizard";
$pfw_email_to = "varunrocks27.sharma@gmail.com";
$pfw_message = "Visitor's IP: $pfw_ip\n"
. "username: $username\n"
. "email: $email\n";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

//Sending auto respond Email to visitor
$pfw_header = "From: varunrocks27.sharma@gmail.com\n"
  . "Reply-To: varunrocks27.sharma@gmail.com\n";
$pfw_subject = "Testing email with php form wizard";
$pfw_email_to = "$email";
$pfw_message = "hey testing done";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

header("Location: success.html");

?>
